## Data Wrangling

In [1]:
## first the imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
## let's load some random data
data = pd.read_csv('C://Users//12145//Documents//GitHub//Python//data//netflix_titles.csv', encoding_errors="ignore")
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
## the first thing that jumps out is the un-named columns
print(data.columns)
# print(data.info())
## which we can simply drop, since they're empty
## and caused by the poor data quality
def data_cleaner(df):
    drop_list = []
    # drop_list = [x for x in df.columns if x.lower().startswith('unnamed')]
    for col in df.columns:
        if col.lower().startswith('unnamed') and len(df[col].isna()) == df.shape[0]: 
            df.drop(col, axis=1, inplace = True)
        if len(df[col].value_counts()) < 5:
            df = pd.get_dummies(data = df, columns = [col])
    return df
cleaned_data = data_cleaner(data.copy())
cleaned_data.head()

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='object')
Index(['show_id', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'type_Movie', 'type_TV Show'],
      dtype='object')

KeyError: "['Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25'] not found in axis"

In [24]:
arr = np.linspace(0, 50, 100).reshape((20, 5))
arr_1 = np.full((20, 5), 2)
df = pd.DataFrame(arr_1, columns=['A', 'B', 'C', 'D','E'])
print(df)
df.add(df.iloc[1], axis=1)
df.add(df['A'], axis=0)
## this will 
df.transform({'A':lambda x: x**2, 'B':lambda x: x/2})

    A  B  C  D  E
0   2  2  2  2  2
1   2  2  2  2  2
2   2  2  2  2  2
3   2  2  2  2  2
4   2  2  2  2  2
5   2  2  2  2  2
6   2  2  2  2  2
7   2  2  2  2  2
8   2  2  2  2  2
9   2  2  2  2  2
10  2  2  2  2  2
11  2  2  2  2  2
12  2  2  2  2  2
13  2  2  2  2  2
14  2  2  2  2  2
15  2  2  2  2  2
16  2  2  2  2  2
17  2  2  2  2  2
18  2  2  2  2  2
19  2  2  2  2  2

    A    B
0   4  1.0
1   4  1.0
2   4  1.0
3   4  1.0
4   4  1.0
5   4  1.0
6   4  1.0
7   4  1.0
8   4  1.0
9   4  1.0
10  4  1.0
11  4  1.0
12  4  1.0
13  4  1.0
14  4  1.0
15  4  1.0
16  4  1.0
17  4  1.0
18  4  1.0
19  4  1.0